### ISSUE TITLE
Directory permission issues using Docker container and add_pkg

### ISSUE THREAD

**Issue by mdlama** [r-wasm/rwasm#41]
I've attempted to use the webR Docker container and followed the instructions on the [Get started](https://r-wasm.github.io/rwasm/articles/rwasm.html) page. However, I get a directory permission error when I attempt to use the function `add_pkg`. Here's the flow of commands and resulting error:

```
> library(rwasm)
Targeting Wasm packages for R 4.4.1
With `WEBR_ROOT` directory: /opt/webr
With `EMSCRIPTEN_ROOT` directory: /opt/emsdk/upstream/emscripten
> add_pkg("deSolve")
v Updated metadata database: 2.21 MB in 4 files.
v Updating metadata database ... done
Processing 1 package(s).
Error: [EACCES] Failed to set permissions for directory './repo': permission denied
```

Indeed, when I exit R and check the `repo` directory, I see that it was created with permissions `dr-xr--r-x`. 

Just in case it's useful, I am on a Mac.

Thanks for you help!

**Comment by georgestagg** [comment]
Related: https://github.com/r-wasm/webr/issues/475

I don't know of a fix yet, but there's a workaround written up in that thread.

**Comment by mdlama** [comment]
Yup, exactly what I'm experiencing. The workaround mentioned worked great for me as well. Feel free to close, and thanks for such a quick response!
